package com.skripsi.lppm.model.enums;

public enum ProposalStatus {
    DRAFT,
    WAITING_MEMBER_APPROVAL,
    WAITING_FACULTY_HEAD,
    WAITING_REVIEWER_RESPONSE,
    REVIEW_IN_PROGRESS,
    REVIEW_COMPLETE,
    WAITING_DEAN_APPROVAL,
    APPROVED_BY_DEAN,
    WAITING_LPPM_APPROVAL,
    LPPM_APPROVED,
    ONGOING,
    PROGRESS_REPORT_SUBMITTED,
    PROGRESS_APPROVED,
    FINAL_REPORT_SUBMITTED,
    FINAL_APPROVED_BY_DEAN,
    FINAL_APPROVED_BY_LPPM,
    COMPLETED
}